server:
  port: 4001
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:4001/eureka/
spring:
  application:
    name: staff-server

